### ISSUE TITLE
autoload-include.php environment variables might be wrong (8.7 LTS fails to start) when linking directories into document root

### ISSUE THREAD

**Issue by AndreasA** [TYPO3-Console/typo3-console-plugin#2]
If one only links the directories into the document root of the webserver then TYPO3_PATH_ROOT will result in wrong directories as 
```
dirname(dirname(dirname(dirname(dirname(__DIR__))))));
```
will result in the target directory being found.
With 8.7 LTS TYPO3 then fails to load as the start directory will be false.

However, without typo3_console this will work as the path is then determined correctly to the webserver document directory.

**Comment by helhum** [comment]
> If one only links the directories into the document root of the webserver

Can you outline the exact directory setup? What folders exactly do you have symlinked?

**Comment by helhum** [comment]
Btw. The plan is to have TYPO3_PATH_ROOT set also in installations without console. So it's not really a TYPO3 Console issue you are facing.

**Comment by AndreasA** [comment]
Ah. OK, in that case I should just set the variable accordingly in the .htaccess or nginx setup and it should work correctly :)

The setup is like this:
/var/www/deploy/current/ is the deployment directory, where typo3_src, vendor, bin etc. are deployed.

Then the corrensponding directories are linked into /var/www/html/
that means that the paths are wrong when using dirname to go back the soft link.

Of course, if I then set the environment variable TYPO3_PATH_ROOT to /var/www/html/ everything is fine.
So if this is the intended behaviour then that is fine.
However, without autoload-include.php setting TYPO3_PATH_ROOT it works without setting that variable.

**Comment by helhum** [comment]
In any case this needs to be discussed / handled within the TYPO3 CMS project

**Comment by AndreasA** [comment]
TYPO3 CMS currently doesn't set TYPO3_PATH_ROOT that way which is why it works there but not with installation of typo3_console but if using TYPO3_PATH_ROOT will in the end be the default behaviour for TYPO3 CMS itself too then it makes sense to handle it there.
